name: Push
on:
  push:
    tags: v[0-9].[0-9]+.[0-9]+
jobs:
  push:
    name: Push tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: bazel run //:push_tag
        env:
          GIT_REF: ${GITHUB_REF#refs/heads/}
